name:
  dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  #- git-annex
  #- uncommitted
  - tmux
  - git
  - vim
  - htop
  # Related to snakemake below:
  - snakemake
  - rpy2
  - pandas
  - xlrd # needed to load excel file with pandas
  - numpy
  - biopython
  - conda

