name:
  dev
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  #- git-annex
  #- uncommitted
  - tmux
  - git
  - vim
  - htop
  # Related to snakemake below:
  - snakemake
  - nextflow
  - rpy2
  - pandas
  - openpyxl == 3.1.0 # needed to load excel file with pandas.
  # See https://stackoverflow.com/a/75471420 for pinned explanation
  - numpy
  - biopython
  - conda

