#' Dependencies generated by Snakemake are defined with a path from the Metaworkflow directory using "smi" variable
#' Bookdown needs to have these file available from the compilation directory and the book directory.
#' This function link file from Metaworkflow directory to these two directories.
linkSmiToRmdAndBookDir <- function(smi,
                                   mw.from.rmd = mw_from_rmd,
                                   book.from.rmd = book_from_rmd) {
  smi_from_rmd <- file.path(mw.from.rmd, smi)
  book_smi_from_rmd <- file.path(book.from.rmd, smi)

  dir.create(dirname(smi), recursive = TRUE, showWarnings = FALSE)
  dir.create(dirname(book_smi_from_rmd), recursive = TRUE, showWarnings = FALSE)

  # if (!file.exists(smi) | tools::md5sum(smi_from_rmd) != tools::md5sum(smi)) {
  if (!file.exists(smi) | file.info(smi_from_rmd)$mtime != file.info(smi)$mtime) {
    message("Copying this file: ", smi)
    # We copy date to use mtime instead of md5sum to check if file was updated
    file.copy(smi_from_rmd, smi, overwrite = TRUE, copy.date = TRUE)
    file.copy(smi_from_rmd, book_smi_from_rmd, overwrite = TRUE, copy.date = TRUE)
  }
  return(invisible(NULL))
}
