name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.13.0
      with:
        directory: .
        args: '--cores 1 --use-conda --conda-cleanup-pkgs cache tests_light'
